### ISSUE TITLE
Meteor package

### ISSUE THREAD

**Issue by dgellow** [TheCognizantFoundry/react-loader#18]
I just want to let you know that I have created a [meteor](https://www.meteor.com/) package for react-loader.
You can find it [here](https://atmospherejs.com/dgellow/react-loader).
It is pretty dumb, it just loads `lib/react-loader.js` and `.node_modules/spin.js/dist/spin.js` as global variables (yeah, it's ugly, but that's how meteor works).

Maybe you are interested to add the package in your repository ? I can create a pull request.

**Comment by kclowes** [comment]
Sure, a PR would be great. Thanks!
