### ISSUE TITLE
Adding a demo would be great!

### ISSUE THREAD

**Issue by gokulkrishh** [TheCognizantFoundry/react-loader#23]
Adding a demo link in README would be great.

**Comment by greenlaw110** [comment]
definitely! And also please add the demo app source code to github repository if possible!

**Comment by gokulkrishh** [comment]
Sure @greenlaw110. I am working on it. I will give a PR once I finish it.

**Comment by Tjorriemorrie** [comment]
![vh947](https://cloud.githubusercontent.com/assets/1099093/11690945/9574ae48-9ea1-11e5-8f33-7637aee79460.jpg)

**Comment by kclowes** [comment]
Added!
