### ISSUE TITLE
Branchs 2.x doesn't exist

### ISSUE THREAD

**Issue by vacho** [TheCognizantFoundry/react-loader#38]
This coment in README is false.

Important Note: The 2.x branch is compatible with React 1.4 and higher. If you're working with an older version of React, please use the 1.x branch.

I only see branch master.

**Comment by urahonky** [comment]
It's the tagged version, just FYI. You should see the 2.x's under the tag.

**Comment by mhuggins** [comment]
https://github.com/quickleft/react-loader/releases

**Comment by kclowes** [comment]
This is now fixed in the README. Thanks!
